name: Publish and Sign Container Image

env:
  # Use docker.io for Docker Hub if empty
  REGISTRY: ghcr.io
  # github.repository as <account>/<repo>
  IMAGE_NAME: ${{ github.repository }}

on:
  schedule:
    - cron: '32 11 * * *'
  push: 
    branches: [ main ]
    # Publish semver tags as releases.
    tags: [ 'v*.*.*' ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
      id-token: write
    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Install cosign
      # https://github.com/marketplace/actions/cosign-installer
      uses: sigstore/cosign-installer@main
      with:
        cosign-release: 'v1.10.0'

    - name: Setup Docker buildx
      # https://github.com/marketplace/actions/docker-setup-buildx
      uses: docker/setup-buildx-action@v2

    - name: Log into ${{ env.REGISTRY }}
      # https://github.com/marketplace/actions/docker-login
      uses: docker/login-action@master
      with:
        registry: ${{ env.REGISTRY }}
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}
  
    - name: Extract Docker metadata
      id: meta
      # https://github.com/marketplace/actions/docker-metadata-action
      # Creats tags and labels inputs for build-push-action, specifically
      # handles mixed case github repos such as MitchellJThomas
      uses: docker/metadata-action@v4
      with:
        images: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}

    - name: Build and push container image
      id: push-step
      # https://github.com/marketplace/actions/build-and-push-docker-images
      uses: docker/build-push-action@master
      with:
        push: true
        tags: ${{ steps.meta.outputs.tags }}
        labels: ${{ steps.meta.outputs.labels }}

    - name: Sign the container image
      env:
        COSIGN_EXPERIMENTAL: "true"
      run: cosign sign ${{ steps.meta.outputs.tags }}@${{ steps.push-step.outputs.digest }}

